sudo: false
language: python
addons:
  apt:
    packages:
      - npm
python:
  - "2.7"
  - "3.5"
  - "3.7"

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=flake8
      install: pip install tox

install:
  - pip install tox-travis
script:
  - tox
