---
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    continue-on-error: true

    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    name: Python ${{ matrix.python-version}}
    steps:
      - uses: actions/checkout@v2.3.5

      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip and install dev requirements
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test
        run: tox
